2018-11-21 07:04:22.385156: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: Tesla K20Xm major: 3 minor: 5 memoryClockRate(GHz): 0.732
pciBusID: 0000:08:00.0
totalMemory: 5.57GiB freeMemory: 5.49GiB
2018-11-21 07:04:22.385220: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-11-21 07:04:22.765581: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-21 07:04:22.765645: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2018-11-21 07:04:22.765657: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2018-11-21 07:04:22.765938: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5278 MB memory) -> physical GPU (device: 0, name: Tesla K20Xm, pci bus id: 0000:08:00.0, compute capability: 3.5)
Using TensorFlow backend.
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7fd4384e0710>>
Traceback (most recent call last):
  File "/home/arbint/.conda/envs/envDeepLearningWithProtoDUNE/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 686, in __del__
TypeError: 'NoneType' object is not callable
2018-11-21 09:26:17.226691: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2018-11-21 09:26:17.226908: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: node01
2018-11-21 09:26:17.226938: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: node01
2018-11-21 09:26:17.227098: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 384.81.0
2018-11-21 09:26:17.227283: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 384.81.0
2018-11-21 09:26:17.227313: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 384.81.0
Using TensorFlow backend.
